#import <Foundation/Foundation.h>
#import "SWGPosts.h"
#import "SWGApi.h"

/**
* UNO-IT
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 0.0.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGAdminApiApi: NSObject <SWGApi>

extern NSString* kSWGAdminApiApiErrorDomain;
extern NSInteger kSWGAdminApiApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Approve post
/// 
///
/// @param postId 
/// 
///  code:200 message:"approved"
///
/// @return 
-(NSURLSessionTask*) appAdminApiV1ApprovePostPostIdPostWithPostId: (NSNumber*) postId
    completionHandler: (void (^)(NSError* error)) handler;


/// Approve with push
/// 
///
/// @param postId 
/// 
///  code:200 message:"approved"
///
/// @return 
-(NSURLSessionTask*) appAdminApiV1ApprovePostWithPushPostIdPostWithPostId: (NSNumber*) postId
    completionHandler: (void (^)(NSError* error)) handler;


/// Get Review Queue
/// 
///
/// 
///  code:200 message:"list of posts"
///
/// @return SWGPosts*
-(NSURLSessionTask*) appAdminApiV1CollectionresponsePostGetWithCompletionHandler: 
    (void (^)(SWGPosts* output, NSError* error)) handler;


/// Get Reviewed Posts
/// pass true to get approved list, pass false for disapproved list
///
/// @param isApprovedList 
/// 
///  code:200 message:"list of posts"
///
/// @return SWGPosts*
-(NSURLSessionTask*) appAdminApiV1CollectionresponsePostIsApprovedListPostWithIsApprovedList: (NSNumber*) isApprovedList
    completionHandler: (void (^)(SWGPosts* output, NSError* error)) handler;


/// Disapprove post
/// 
///
/// @param postId 
/// 
///  code:200 message:"disapproved"
///
/// @return 
-(NSURLSessionTask*) appAdminApiV1DisapprovePostPostIdPostWithPostId: (NSNumber*) postId
    completionHandler: (void (^)(NSError* error)) handler;


/// Edit post
/// 
///
/// @param postId 
/// @param content 
/// @param photoURL  (optional)
/// @param title  (optional)
/// 
///  code:200 message:"disapproved"
///
/// @return 
-(NSURLSessionTask*) appAdminApiV1EditPostPostIdPostWithPostId: (NSNumber*) postId
    content: (NSString*) content
    photoURL: (NSString*) photoURL
    title: (NSString*) title
    completionHandler: (void (^)(NSError* error)) handler;


/// Feature Post
/// 
///
/// @param postId 
/// 
///  code:200 message:"featured"
///
/// @return 
-(NSURLSessionTask*) appAdminApiV1FeaturePostPostIdPostWithPostId: (NSNumber*) postId
    completionHandler: (void (^)(NSError* error)) handler;


/// Delete post
/// 
///
/// @param postId 
/// 
///  code:200 message:"deleted"
///
/// @return 
-(NSURLSessionTask*) appAdminApiV1PostPostIdDeleteWithPostId: (NSNumber*) postId
    completionHandler: (void (^)(NSError* error)) handler;


/// Feature Post
/// 
///
/// @param postId 
/// 
///  code:200 message:"featured"
///
/// @return 
-(NSURLSessionTask*) appAdminApiV1UnFeaturePostPostIdPostWithPostId: (NSNumber*) postId
    completionHandler: (void (^)(NSError* error)) handler;



@end
