#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* UNO-IT
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 0.0.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SWGDataVersion
@end

@interface SWGDataVersion : SWGObject

/* the timestamp when posts were last updated [optional]
 */
@property(nonatomic) NSNumber* updateTimeStamp;

@end
