#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* UNO-IT
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 0.0.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SWGPost1
@end

@interface SWGPost1 : SWGObject


@property(nonatomic) NSString* authorEmail;

@property(nonatomic) NSString* authorName;

@property(nonatomic) NSString* reviewedBy;

@property(nonatomic) NSNumber* reviewTimeStamp;

@property(nonatomic) NSNumber* isReviewed;

@property(nonatomic) NSNumber* isApproved;

@property(nonatomic) NSNumber* timeStamp;

@property(nonatomic) NSString* postTitle;

@property(nonatomic) NSString* category;

@property(nonatomic) NSNumber* isFeatured;

@property(nonatomic) NSString* postContent;

@property(nonatomic) NSString* photoUrl;

@property(nonatomic) NSNumber* sendPushNotifications;

@property(nonatomic) NSString* authorFirebaseUID;

@property(nonatomic) NSString* authorProfilePic;

@property(nonatomic) NSNumber* isVotingPost;

@property(nonatomic) NSNumber* voteUpdateTimestamp;

@property(nonatomic) NSArray<NSString*>* candidateNames;

@property(nonatomic) NSArray<NSNumber*>* voteCounts;

@end
