#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* UNO-IT
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 0.0.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SWGParams
@end

@interface SWGParams : SWGObject


@property(nonatomic) NSString* email;

@property(nonatomic) NSString* firebaseUID;

@property(nonatomic) NSString* gcmInstanceId;

@property(nonatomic) NSString* name;

@property(nonatomic) NSString* profilePic;

@end
